apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

# patchesStrategicMerge:
# - argocd-cm.yaml
# - argocd-rbac-cm.yaml
# - argocd-server.yaml

patchesJson6902:
- path: argocd-server-deploy-command.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1
